[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = esptool

# Te flagi są kluczowe dla stabilnego połączenia
monitor_dtr = 0
monitor_rts = 0

# Zostawiamy TYLKO to. Usunięcie send_on_enter przywróci tryb RAW
monitor_filters = direct, esp32_exception_decoder
monitor_echo = yes
monitor_eol = LF

build_flags = 
    -I include
    -D HARDWARE_ESP32_DEV